/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as EmailAssistantRouteImport } from './routes/email-assistant'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as SummariserRouteImport } from './routes/summariser'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAssistantRoute = EmailAssistantRouteImport.update({
  id: '/email-assistant',
  path: '/email-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SummariserRoute = SummariserRouteImport.update({
  id: '/summariser',
  path: '/summariser',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/clients': typeof ClientsRoute
  '/email-assistant': typeof EmailAssistantRoute
  '/enquiries': typeof EnquiriesRoute
  '/properties': typeof PropertiesRoute
  '/summariser': typeof SummariserRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/clients': typeof ClientsRoute
  '/email-assistant': typeof EmailAssistantRoute
  '/enquiries': typeof EnquiriesRoute
  '/properties': typeof PropertiesRoute
  '/summariser': typeof SummariserRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/clients': typeof ClientsRoute
  '/email-assistant': typeof EmailAssistantRoute
  '/enquiries': typeof EnquiriesRoute
  '/properties': typeof PropertiesRoute
  '/summariser': typeof SummariserRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/clients'
    | '/email-assistant'
    | '/enquiries'
    | '/properties'
    | '/summariser'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/clients'
    | '/email-assistant'
    | '/enquiries'
    | '/properties'
    | '/summariser'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/clients'
    | '/email-assistant'
    | '/enquiries'
    | '/properties'
    | '/summariser'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ClientsRoute: typeof ClientsRoute
  EmailAssistantRoute: typeof EmailAssistantRoute
  EnquiriesRoute: typeof EnquiriesRoute
  PropertiesRoute: typeof PropertiesRoute
  SummariserRoute: typeof SummariserRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-assistant': {
      id: '/email-assistant'
      path: '/email-assistant'
      fullPath: '/email-assistant'
      preLoaderRoute: typeof EmailAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summariser': {
      id: '/summariser'
      path: '/summariser'
      fullPath: '/summariser'
      preLoaderRoute: typeof SummariserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ClientsRoute: ClientsRoute,
  EmailAssistantRoute: EmailAssistantRoute,
  EnquiriesRoute: EnquiriesRoute,
  PropertiesRoute: PropertiesRoute,
  SummariserRoute: SummariserRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
